/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PineappleIndexImport } from './routes/pineapple/index'
import { Route as KiwiIndexImport } from './routes/kiwi/index'
import { Route as AboutIndexImport } from './routes/about/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PineappleIndexRoute = PineappleIndexImport.update({
  id: '/pineapple/',
  path: '/pineapple/',
  getParentRoute: () => rootRoute,
} as any)

const KiwiIndexRoute = KiwiIndexImport.update({
  id: '/kiwi/',
  path: '/kiwi/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/kiwi/': {
      id: '/kiwi/'
      path: '/kiwi'
      fullPath: '/kiwi'
      preLoaderRoute: typeof KiwiIndexImport
      parentRoute: typeof rootRoute
    }
    '/pineapple/': {
      id: '/pineapple/'
      path: '/pineapple'
      fullPath: '/pineapple'
      preLoaderRoute: typeof PineappleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/kiwi': typeof KiwiIndexRoute
  '/pineapple': typeof PineappleIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/kiwi': typeof KiwiIndexRoute
  '/pineapple': typeof PineappleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/kiwi/': typeof KiwiIndexRoute
  '/pineapple/': typeof PineappleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/kiwi' | '/pineapple'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/kiwi' | '/pineapple'
  id: '__root__' | '/' | '/about/' | '/kiwi/' | '/pineapple/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  KiwiIndexRoute: typeof KiwiIndexRoute
  PineappleIndexRoute: typeof PineappleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  KiwiIndexRoute: KiwiIndexRoute,
  PineappleIndexRoute: PineappleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about/",
        "/kiwi/",
        "/pineapple/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/kiwi/": {
      "filePath": "kiwi/index.tsx"
    },
    "/pineapple/": {
      "filePath": "pineapple/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
